baseURL = "https://qwc-services.github.io/qwc-website/"
languageCode = "en-us"
title = "QWC2 Documentation"

# https://learn.netlify.app/
theme = "hugo-theme-learn"

[params]
editURL = "https://github.com/qwc-services/qwc-website/edit/main/content/"
description = "Documentation QWC2 and QWC services"
themeVariant = "green"
disableNextPrev = true
disableMermaid = true

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
